### ISSUE TITLE
cuisine fires an error, making real filing cabinets unusable

### ISSUE THREAD

**Issue by Yoghurt4C** [Snownee/Cuisine#16]
happens when putting any folder from RFC with an item in it into a crafting grid
https://paste.dimdev.org/musiqicoha.mccrash

**Comment by 3TUSK** [comment]
Most likely on Real Filing Cabinet's side. We can add a safe-guard on this though because we do rely on some unusual assumptions. I need further research on this one... it has to do with the contract of `hasCapability` and `getCapability`.

Remark: at the time I am writing this, I found this in RFC's codebase, which I believe is where the problem arises from.
https://github.com/bafomdad/realfilingcabinet/blob/a686899252740693e0719df98f5f59bc05adecde/com/bafomdad/realfilingcabinet/items/capabilities/CapabilityProviderFolder.java#L60

**Comment by 3TUSK** [comment]
Forwarded to bafomdad/realfilingcabinet#46.

**Comment by Yoghurt4C** [comment]
resolved in https://github.com/bafomdad/realfilingcabinet/commit/78868f6f50457e26d4f4dd37d6e1f8a53ea95f27
