### ISSUE TITLE
Serene Season compatibility

### ISSUE THREAD

**Issue by MilchLos** [Snownee/Cuisine#40]
Will there be compatibility with Serene Seasons in the near future?

**Comment by erisdev** [comment]
this is something you can configure yourself, actually! open up `config/sereneseasons/cropfertility.cfg` and you'll find that there is a list of crops for each season. you can add the item id of either the crops or the seeds to whichever list is appropriate.

as for out of the box support, i think it falls on the serene seasons folks to include cuisine in their defaults.

**Comment by Snownee** [comment]
@erisdev Thanks for your help!

The problem is Serene Seasons assume the item and block of a crop use the same resource id and have no metadata, which makes Cuisine impossible to perfectly support Serene Seasons' configuration. So we prefer pack makers to configure themselves. I think things will be better after flattening in Minecraft 1.13.

**Comment by erisdev** [comment]
oh, my mistake! i admit i didn't actually test serene seasons with cuisine yet. i was speaking from experience with rustic's crops. i didn't know cuisine's foods shared an item id
