### ISSUE TITLE
Can't get basin to work

### ISSUE THREAD

**Issue by viceroy369** [Snownee/Cuisine#44]
I try putting fruit in the basin, either placing it or throwing it in and nothing happens. Am I missing something?

**Comment by 3TUSK** [comment]
For those who are looking at this:
 - You want to put a piston atop basin in order to "squeeze" fruit.
 - Alternatively you can just jump and fall on basin to "squeeze" fruit.
 - Only certain recipes require just "throwing them into basin" which requires basin holding corresponding fluid.
 - JEI is your friend.

**Comment by Snownee** [comment]
- Patchouli is your friend as well.
