### ISSUE TITLE
Terrafirmacraft Log Render Issue

### ISSUE THREAD

**Issue by drhaber** [Snownee/Cuisine#80]
TFC TNG logs META 0 are an item while Meta 5 in the standard upwards facing log

By default the chopping board appears as such
![image](https://user-images.githubusercontent.com/56454522/78170075-69248d00-7420-11ea-82e9-b52e9b88b788.png)

When attempting to give myself a chopping board with the proper META ID I get the Black and Purple error texture instead. `cuisine:chopping_board 1 1 {BlockEntityTag: {cover: {id: "tfc:wood/log/acacia", Count: 1b, Damage: 5s}}}`
![image](https://user-images.githubusercontent.com/56454522/78170300-bf91cb80-7420-11ea-880e-105765027740.png)

**Comment by 3TUSK** [comment]
Nice, I _know_ that one day I will see that my assumption encounters an exception.

So the issue is simple, TFC's log item are bit special. My assumption is that the item has a _block_ model, not a standard item model with just 1 layer pixels. TFC's log breaks my assumption. Well, I shouldn't have that assumption from the beginning of time either.
When you try giving yourself things like `cuisine:chopping_board 1 1 {BlockEntityTag: {cover: {id: "tfc:wood/log/acacia", Count: 1b, Damage: 5s}}}`: I believe that there is no item with id of `tfc:wood/log/acacia`, this one will of course not work.

I am not certain about the fix tho. I can make a list of items with special treatment; this part is simple. The main problem is my limited time.

**Comment by drhaber** [comment]
Ah makes sense `tfc:wood/log/acacia:5` has no Item Texture.
I'll use the plank version or make a Hidden Item with Content Tweaker for the sake of the pack.

**Comment by 3TUSK** [comment]
Still need to wait for new release. After the new release, let me know if my fix works or not.

**Comment by 3TUSK** [comment]
@drhaber Please try this https://www.curseforge.com/minecraft/mc-mods/cuisine/files/2921476 version.

**Comment by drhaber** [comment]
There we go! Thank you!
